# Site Info
title:              "Delapan Piksel"
description:        "Kumpulan tulisan opini dari Jaka Santana"
excerpt:            "Kumpulan tulisan opini dari Jaka Santana"
google_verify:      # Put your Google Verification here
google_analytics:   # Put your Google Analytics code

# Author Info
author_name:        "Jaka Santana" # Your name here
author_email:       jakasantana88@gmail.com # Your email here
author_gravatar:    287de6c6c6b38b1f34963b4b126f4a63 # Your Gravatar md5 hash here for logo
twitter_username:   delapanpx # Your Twitter username here
github_username:    delapanpx # Your GitHub username here

# Site Settings
url:                # main url
baseurl:            # for gh-pages
permalink:          /:title # Post permalink
timezone:           Asia/Jakarta # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            false  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt", "_pages" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
